### ISSUE TITLE
ModuleNotFoundError: No module named 'pystac_client'

### ISSUE THREAD

**Issue by keepfighting666** [nasa/LHASA#24]
![image](https://github.com/user-attachments/assets/05301427-fe4d-46b1-9d51-ebd5a4c901a0)

**Comment by keepfighting666** [comment]
what can i do to fix it?

**Comment by keepfighting666** [comment]
ok, I have fixed it.

**Comment by thomasastanley** [comment]
Glad it's fixed. For those who get the first error (failing to download IMERG 6E), note that the LHASA master branch is currently out of date. The fix is available in the [dev](https://github.com/nasa/LHASA/tree/dev) branch, but this version is not quite ready for release. 

If you don't want to switch to the dev version, you can also use the CLI to point LHASA to the latest IMERG data: `python lhasa.py -iv 07B`
